[oneAPI_Support_Headers]
git-tree-sha1 = "6bdff1b9390a256898c673ff21f72f2fcc31b7aa"

    [[oneAPI_Support_Headers.download]]
    sha256 = "a5ee1355254ec363b4ab303d6e31ba45ae78cf181259b34f1d5e081a5c0f8219"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_Headers_jll.jl/releases/download/oneAPI_Support_Headers-v2023.2.0+0/oneAPI_Support_Headers.v2023.2.0.any.tar.gz"
