[oneAPI_Support_Headers]
git-tree-sha1 = "0f4191ff768d1b3c089f9ef9f2ab8187cf4f7a9a"

    [[oneAPI_Support_Headers.download]]
    sha256 = "053b94153a9edcb55086e4edcf5e3fee53dc2ee7da908bc414b54027b0ecf8ef"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_Headers_jll.jl/releases/download/oneAPI_Support_Headers-v2025.0.0+0/oneAPI_Support_Headers.v2025.0.0.any.tar.gz"
