[oneAPI_Support_Headers]
git-tree-sha1 = "04fd46500e9fb47542d178b258491e3b5588ee90"

    [[oneAPI_Support_Headers.download]]
    sha256 = "74d4d889405862674805c60aab6858c2db34eb5020fa9528234e6dc854cd422c"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_Headers_jll.jl/releases/download/oneAPI_Support_Headers-v2025.1.0+0/oneAPI_Support_Headers.v2025.1.0.any.tar.gz"
