[oneAPI_Support_Headers]
git-tree-sha1 = "f01b2b942e15499486e2d5da9b9db0eccd491b47"

    [[oneAPI_Support_Headers.download]]
    sha256 = "152b1ed9d208db91f958db38f086c2869b1a5ed58e36edcf1febe9d230a7c874"
    url = "https://github.com/JuliaBinaryWrappers/oneAPI_Support_Headers_jll.jl/releases/download/oneAPI_Support_Headers-v2025.3.1+0/oneAPI_Support_Headers.v2025.3.1.any.tar.gz"
