# Autogenerated wrapper script for oneAPI_Support_Headers_jll for any
export mkl_hpp

JLLWrappers.@generate_wrapper_header("oneAPI_Support_Headers")
JLLWrappers.@declare_file_product(mkl_hpp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        mkl_hpp,
        "include/oneapi/mkl.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
